# Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
- index.md
- who.md
- how.md

footer: 'follow us on <a href="https://twitter.com/verifieralliance">twitter | 
                      <a href="https://warpcast.com/verifieralliance.eth"></a>'

style: dark
listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-console
